const About= ()=>{
    return (
        <div>
            <h1>About Us</h1>
            <h3>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia cupiditate quis possimus illum porro consequatur facere, vel quae itaque labore dignissimos commodi, hic necessitatibus officia ratione sunt excepturi unde repudiandae quas. Odio dignissimos ad ab excepturi neque, nam adipisci ducimus fugit, architecto nesciunt sint quia! Consectetur illum dolorem hic totam nobis expedita commodi unde voluptates iusto deserunt harum exercitationem, blanditiis tempore maxime modi accusantium molestiae eum facilis dolor alias fugit sit. Amet voluptatem eveniet illo, corrupti dolores iusto nisi porro minus perferendis ratione fuga provident quasi sunt, delectus ab hic velit. Labore, soluta illo blanditiis inventore adipisci quam. Itaque dolorum minima, quia enim eos totam quisquam, consequuntur distinctio molestiae culpa dignissimos reiciendis sint veniam maiores quis. In iste natus corrupti suscipit maiores sint animi quis nihil cupiditate sunt sed aspernatur laboriosam adipisci corporis, non enim praesentium hic, quae ipsum. Nesciunt et laborum provident, iusto maxime nemo voluptatum exercitationem commodi aliquid odit qui! Praesentium sunt iste quam commodi doloremque pariatur perferendis inventore quo? Quae voluptas dicta repellendus cumque veniam minus tempora? Minus temporibus modi perferendis hic deserunt nam repudiandae quaerat aliquam, officiis eveniet tenetur blanditiis iure ipsa molestias neque nobis doloribus ea ipsam. Molestias dolorum cum voluptatibus nemo, a dolores sequi. Quidem adipisci vero reiciendis eveniet pariatur ea provident iste temporibus explicabo dignissimos eius id harum repellat, nulla tempore, non ullam? Numquam eius sed hic sequi repellendus, dolore a aspernatur delectus quaerat nisi impedit voluptatibus distinctio perspiciatis modi! Odio recusandae distinctio esse molestias nisi, temporibus quod quisquam ex sit incidunt consectetur id quibusdam, rem, quasi autem vitae. Expedita, eum aut culpa dicta nostrum, veniam eveniet ad minus suscipit praesentium temporibus consectetur officia nihil, deleniti nesciunt voluptate fugiat quis fuga delectus aliquam cumque pariatur. Ipsa aperiam doloremque, repudiandae eum eaque ducimus eveniet quam ipsum laudantium ea eos modi, harum expedita enim sapiente?</h3>
        
        </div>
    );
}

export default About;